import { useState } from "react";
import { Link, useSearchParams } from "react-router-dom";
import { AgentFocusView } from "./AgentFocusView";
import { Activity, ArrowRight, Bot, Check, CircleDollarSign, Clock3, ExternalLink, Mail, Megaphone, PackageSearch, Play, RefreshCw, Search, Sparkles, Truck, Users, WalletCards, X } from "lucide-react";
import { agentActivity, agentDefinitions, approvedActionPath, chileDay, proposalDestinations, statusLabels, type AgentTask, type AgentType, type Proposal, type AgentActionItem, type RiskAlert, type Connection, type Delivery } from "./agent-center";
import "./agentsDashboard.css";
export type AgentCenterData = { tasks: AgentTask[]; activity: AgentTask[]; proposals: Proposal[]; actions: AgentActionItem[]; alerts: RiskAlert[]; connections: Connection[]; delivery: Delivery | null; totals: { proposals: number | null; actions: number | null; alerts: number | null }; schedule: { morning_time: string; timezone: string; email_enabled: boolean } | null };
type Props = { data: AgentCenterData; loading: boolean; notice: string; busy: string; canManage: boolean; refresh: () => void; request: (type: AgentType) => void; decide: (id: string, decision: "approved" | "rejected") => void; more: () => void };
const icons = { executive: Sparkles, commercial: Users, finance: CircleDollarSign, collections: WalletCards, marketing: Megaphone, logistics: Truck, foreign_trade: PackageSearch };
const dateText = (v?: string | null) => v ? new Intl.DateTimeFormat("es-CL", { dateStyle: "short", timeStyle: "short", timeZone: "America/Santiago" }).format(new Date(v)) : "Sin informe";
const amount = (v: unknown) => typeof v === "number" && Number.isFinite(v) ? v.toLocaleString("es-CL", { maximumFractionDigits: 0 }) : "No disponible";
export function AgentsDashboard({ data, loading, notice, busy, canManage, refresh, request, decide, more }: Props) {
  const [params] = useSearchParams();
  const [filter, setFilter] = useState("all"), [search, setSearch] = useState(""), [tab, setTab] = useState("pending"), [day, setDay] = useState<string | null>(null);
  const activity = agentActivity(data.activity), max = Math.max(1, ...activity.map((d) => d.total));
  const latest = (type: AgentType) => data.tasks.find((task) => task.agent_type === type);
  const ready = agentDefinitions.filter((a) => latest(a.type)?.status === "completed").length;
  const running = agentDefinitions.filter((a) => ["in_progress", "pending"].includes(latest(a.type)?.status || "")).length;
  const filtered = agentDefinitions.filter((a) => `${a.title} ${a.source}`.toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g, "").includes(search.toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g, "")) && (filter === "all" || (filter === "ready" ? latest(a.type)?.status === "completed" : latest(a.type)?.status === "failed")));
  const history = data.activity.filter((t) => !day || chileDay(t.created_at) === day).slice(0, 40);
  const focus = params.get("focus") || "";
  if (["proposals", "inventory", "connection"].includes(focus)) return <AgentFocusView {...{ data, focus, loading, notice, busy, canManage, refresh, more, decide }} provider={params.get("provider")} />;
  return <section className="agents-center" aria-busy={loading}>
    <header className="ac-heading"><div><span className="eyebrow">CLIMACTIVA / OPERACIONES</span><h1>Centro de agentes</h1><p>{new Intl.DateTimeFormat("es-CL", { dateStyle: "full", timeZone: "America/Santiago" }).format(new Date())}</p></div><button className="ac-icon" title="Actualizar informes" aria-label="Actualizar informes" disabled={loading} onClick={refresh}><RefreshCw size={20} className={loading ? "ac-spin" : ""} /></button></header>
    {notice && <p className="notice-banner warning" role="alert">{notice}</p>}
    <section className="ac-overview" aria-label="Resumen de agentes">
      <div className="ac-daily"><div className="ac-daily-title"><Clock3 size={24} /><span>INFORME GERENCIAL</span></div><div className="ac-noon"><strong>{data.schedule ? data.schedule.morning_time.slice(0, 5) : "--:--"}</strong><span>Hora de Chile<br />{data.schedule?.morning_time.startsWith("12:00") ? "Un informe al dia" : "Agenda pendiente de actualizar"}</span></div><p>{data.delivery ? `${statusLabels[data.delivery.status] || data.delivery.status} · ${dateText(data.delivery.sent_at || data.delivery.created_at)}` : "Sin entrega registrada"}</p><Link to="/agentes/executive/dashboard">Ver informe del gerente <ArrowRight size={18} /></Link></div>
      <div className="ac-health"><button onClick={() => setFilter("ready")}><span className="ac-dot green" />Informes listos<strong>{loading ? "..." : `${ready} / 7`}</strong></button><button onClick={() => { setTab("pending"); document.getElementById("agent-workspace")?.scrollIntoView({ behavior: "smooth" }); }}><span className="ac-dot amber" />Decisiones pendientes<strong>{data.totals.proposals ?? "--"}</strong></button><div><span className="ac-dot blue" />En proceso<strong>{loading ? "..." : running}</strong></div></div>
      <div className="ac-activity"><div className="ac-section-heading"><h2>Actividad · 7 dias</h2><Activity size={19} /></div><div className="ac-chart">{activity.map((item) => <button key={item.day} title={`${item.day}: ${item.completed} completados, ${item.failed} fallidos, ${item.total} tareas`} aria-label={`Ver actividad del ${item.day}: ${item.total} tareas`} onClick={() => { setTab("activity"); setDay(item.day); document.getElementById("agent-workspace")?.scrollIntoView({ behavior: "smooth" }); }}><span>{item.total}</span><i style={{ height: `${Math.max(3, item.total / max * 72)}px` }}><b style={{ height: `${item.total ? item.failed / item.total * 100 : 0}%` }} /></i><small>{item.label}</small></button>)}</div><p><span className="ac-dot teal" />Tareas registradas <span className="ac-dot rose" />Fallidas</p></div>
    </section>
    <section className="ac-team" aria-label="Agentes y sus modulos"><div className="ac-toolbar"><div className="ac-segments" role="group" aria-label="Filtrar agentes">{[["all", "Todos"], ["ready", "Listos"], ["attention", "Con error"]].map(([key, label]) => <button key={key} aria-pressed={filter === key} onClick={() => setFilter(key)}>{label}</button>)}</div><label className="ac-search"><Search size={18} /><input aria-label="Buscar agente o modulo" placeholder="Buscar agente o modulo" value={search} onChange={(e) => setSearch(e.target.value)} /></label></div>
      <div className="ac-agent-grid">{filtered.map((a) => { const task = latest(a.type), Icon = icons[a.type], active = ["pending", "in_progress"].includes(task?.status || ""); return <article key={a.type} className={`ac-agent ${a.color}`}><header><span className="ac-agent-icon"><Icon size={23} /></span><span className={`ac-status ${task?.status || "empty"}`}>{statusLabels[task?.status || ""] || "Sin ejecutar"}</span></header><Link className="ac-agent-name" to={`/agentes/${a.type}/dashboard`}><h2>{a.title}</h2><ArrowRight size={18} /></Link><Link className="ac-source" to={a.href}>{a.source}<ExternalLink size={12} /></Link><div className="ac-agent-metric"><span>{a.metricLabel}</span><strong>{task?.status === "completed" ? amount(task.result?.metrics?.[a.metric]) : "--"}</strong>{a.metric === "operating_profit" && task?.result?.warnings?.some((w) => /provisional/i.test(w)) && <small>Provisional</small>}</div><footer><small>{dateText(task?.created_at)}</small><button className="ac-icon" aria-label={`Analizar ${a.title}`} title={`Analizar ${a.title} sin enviar mensajes`} disabled={!canManage || Boolean(busy) || active} onClick={() => request(a.type)}>{active || busy === a.type ? <RefreshCw size={18} className="ac-spin" /> : <Play size={18} />}</button></footer></article>; })}</div>
      {!filtered.length && <p className="ac-empty">No hay agentes que coincidan con el filtro.</p>}
    </section>
    <section className="ac-workspace" id="agent-workspace"><div role="tablist" aria-label="Gestion de agentes" className="ac-tabs">{[["pending", `Pendientes (${data.totals.proposals ?? "--"})`], ["activity", "Actividad"], ["connections", "Conexiones"]].map(([key, label]) => <button role="tab" id={`ac-tab-${key}`} aria-controls={`ac-panel-${key}`} aria-selected={tab === key} key={key} onClick={() => { setTab(key); if (key === "activity") setDay(null); }}>{label}</button>)}</div>
      <div role="tabpanel" id={`ac-panel-${tab}`} aria-labelledby={`ac-tab-${tab}`}>
      {tab === "pending" && <><div className="ac-section-heading"><h2>Decisiones por revisar</h2><small>{data.proposals.length} de {data.totals.proposals ?? "--"}</small></div>{data.proposals.map((p) => <details key={p.id} className="ac-proposal"><summary><span className={`ac-dot ${p.risk_level === "high" ? "rose" : "amber"}`} /><span>{p.title}<small>{dateText(p.created_at)} · {proposalDestinations[p.kind] || p.kind}</small></span></summary><p>{p.summary}</p><div className="ac-proposal-actions"><button disabled={!canManage || Boolean(busy)} onClick={() => decide(p.id, "rejected")}><X size={17} />Rechazar</button><button disabled={!canManage || Boolean(busy)} onClick={() => decide(p.id, "approved")}><Check size={17} />Aprobar</button></div></details>)}{!loading && !data.proposals.length && <p className="ac-empty"><Check size={22} />Sin decisiones pendientes.</p>}
        <details className="ac-history"><summary>Acciones aprobadas · {data.totals.actions ?? "--"}</summary>{data.actions.map((a) => <Link key={a.id} to={approvedActionPath(a)}><span>{a.title}<small>{dateText(a.created_at)}</small></span><ArrowRight size={17} /></Link>)}</details><details className="ac-history"><summary>Alertas de inventario · {data.totals.alerts ?? "--"}</summary>{data.alerts.map((a) => <Link key={a.id} to="/agentes/logistics/dashboard"><span>{a.sku} · {a.title}<small>{a.detail}</small></span><ArrowRight size={17} /></Link>)}{!data.alerts.length && <p>Sin alertas abiertas registradas.</p>}</details>
        {(data.proposals.length < (data.totals.proposals || 0) || data.actions.length < (data.totals.actions || 0) || data.alerts.length < (data.totals.alerts || 0)) && <button className="ac-more" onClick={more} disabled={loading}>Cargar mas registros</button>}</>}
      {tab === "activity" && <><div className="ac-section-heading"><h2>{day ? `Actividad del ${day}` : "Ultimos analisis"}</h2>{day && <button className="ac-icon" aria-label="Quitar filtro de fecha" title="Quitar filtro de fecha" onClick={() => setDay(null)}><X size={18} /></button>}</div>{history.map((t) => <Link key={t.id} className="ac-activity-row" to={`/agentes/${t.agent_type}/dashboard?task=${t.id}`}><Bot size={20} /><span><strong>{agentDefinitions.find((a) => a.type === t.agent_type)?.title || t.agent_type}</strong><small>{dateText(t.created_at)}</small></span><span className={`ac-status ${t.status}`}>{statusLabels[t.status] || t.status}</span><ArrowRight size={16} /></Link>)}{!history.length && <p className="ac-empty">Sin analisis en este periodo.</p>}{history.length === 40 && <p>Ultimos 40 analisis. El historial completo esta en cada agente.</p>}</>}
      {tab === "connections" && <><h2>Estado de las fuentes</h2>{data.connections.map((c) => <div className="ac-connection" key={c.provider}><span className={`ac-dot ${c.status === "connected" ? "green" : "amber"}`} /><span><strong>{c.provider}</strong><small>Ultima conexion: {dateText(c.last_success_at)}</small><small>{c.message}</small></span><span className="ac-status">{statusLabels[c.status] || c.status}</span></div>)}<Link className="ac-more" to="/administracion">Administracion de conexiones <ExternalLink size={16} /></Link></>}
      </div>
    </section>
    <p className="ac-footnote"><Mail size={15} />{data.schedule?.email_enabled ? "Correo gerencial activo" : "Correo gerencial sin confirmar"} · Analisis manuales sin envio automatico.</p>
  </section>;
}
