import { Link } from 'react-router-dom';
import { BarChart3 } from 'lucide-react';
import { marketTopTen } from './marketMath';
import './market-study.css';
const marketMoney=(v:number|null|undefined)=>v==null?'Sin dato':v.toLocaleString('es-CL',{style:'currency',currency:'CLP',maximumFractionDigits:2});
const percent=(v:number|null)=>v==null?'No calculable':`${v.toLocaleString('es-CL',{maximumFractionDigits:2})}%`;
const date=(v:string|null)=>v?new Date(v.length===10?v+'T12:00:00Z':v).toLocaleString('es-CL',{timeZone:'America/Santiago'}):'Sin fecha';
export function OpportunityTable({ranking}:{ranking:ReturnType<typeof marketTopTen>}){
 return <><p className="market-muted">{ranking.rows.length} oportunidades mostradas · {ranking.eligible} elegibles de {ranking.total} referencias. Sin completar posiciones con datos incompletos.</p>
 {!ranking.rows.length?<div className="market-empty"><BarChart3 size={30}/><h3>Aún no hay oportunidades con respaldo suficiente</h3><p>Revisa equivalencias, costo, precio, fechas y disponibilidad. Una lista vacía no significa que no haya oportunidades comerciales.</p></div>:<div className="market-table-wrap"><table><thead><tr><th>Producto</th><th>Condición</th><th>Venta neta</th><th>Mercado neto</th><th>Utilidad bruta/u.</th><th>Margen</th><th>Motivo y puntaje</th></tr></thead><tbody>{ranking.rows.map((r,i)=><tr key={r.product.key}><td><Link to={`/estudio-mercado?product=${encodeURIComponent(r.product.key)}&tab=simulator`}>{i+1}. {r.product.name}</Link><small>{r.product.sku}</small></td><td>{r.product.mode==='transit'?'Teórica · en tránsito':'Stock registrado'}<small>{r.product.mode==='transit'?`ETA ${date(r.product.eta)}`:`${r.product.stock} unidades registradas; confirmar reservas`}</small></td><td>{marketMoney(r.price)}</td><td>{marketMoney(r.median)}<small>{r.comparable.length} oferentes comparables</small>{r.comparable.map(o=><small key={o.observation.id}>{o.observation.payload.seller} · {date(o.observation.payload.observed_at)}</small>)}</td><td>{marketMoney(r.simulation.before.unitProfit)}<small>{r.product.mode==='transit'?'Costo estimado':'Según costo registrado'}</small></td><td>{percent(r.margin)}</td><td>Precio {percent(r.advantage)} bajo mediana<small>Confianza {percent((r.confidence||0)*100)} · puntaje {r.score?.toFixed(2)}</small></td></tr>)}</tbody></table></div>}
 <details className="market-method"><summary>Cómo se calcula y qué queda fuera</summary><p>Puntaje = menor valor entre margen bruto (%) y ventaja de precio frente a mediana (%) × menor confianza de las ofertas comparables. Se ordena por puntaje, luego margen y clave de producto. Una oferta vigente por oferente; IVA y moneda normalizados, unidad y equivalencia aprobadas.</p><p>Máximo 30 días para investigación, costo y precio; 2 días para stock; 7 días para tipo de cambio; confianza mínima 70%. En tránsito exige ETA no vencida y supuestos completos. Proveedores, coincidencias dudosas, pérdidas y datos antiguos quedan fuera. No mide demanda ni garantiza venta, recepción o stock libre de reservas.</p></details></>;
}
