import { useCallback, useEffect, useRef, useState } from "react";
import { Archive, Edit, Plus, RefreshCw, Send, X, Save, Search } from "lucide-react";
import { useAuth } from "../auth/AuthContext";
import { whatsappRequest } from "../../lib/whatsappApi";
interface TemplateDraft {internalName:string;name:string;language:string;category:string;header:string;body:string;footer:string;description:string;bindings:Array<{key:string;field:string;example:string}>;buttons:Array<{type:string;text:string;value?:string}>;purposeConfirmed?:boolean}
interface TemplatePolicy {revision:string;verifiedAt:string;graphVersion:string;categories:string[];languages:string[];limits:Record<string,number>;source:string}

export interface ManagedTemplate {
  id:string;internal_name:string;meta_template_name:string;language:string;category:string;preview_body:string;description:string;
  components:Array<{type:string;text?:string;buttons?:Array<{type:string;text:string;url?:string;phone_number?:string}>}>;
  variable_bindings:TemplateDraft["bindings"];draft:TemplateDraft|null;local_state:string;status:string;meta_template_id:string|null;
  rejected_reason:string|null;last_synced_at:string|null;created_at:string;updated_at:string;revision:number;active:boolean;editBlockedReason?:string|null;
}
interface ManagementResponse {templates:ManagedTemplate[];policy:TemplatePolicy;variableFields:string[];configuration:{wabaId:string;phoneNumberId:string;graphVersion:string;blockers:string[];webhookFields:string[]}}
const labels:Record<string,string>={DRAFT:"BORRADOR",SUBMITTING:"ENVIANDO",UNCERTAIN:"POR VERIFICAR",PENDING:"PENDIENTE",APPROVED:"APROBADA",REJECTED:"RECHAZADA",PAUSED:"PAUSADA",DISABLED:"DESHABILITADA",ARCHIVED:"ARCHIVADA",DELETED:"ELIMINADA",IN_APPEAL:"EN APELACIÓN",LIMIT_EXCEEDED:"LÍMITE EXCEDIDO",PENDING_DELETION:"ELIMINACIÓN PENDIENTE",UNAVAILABLE:"NO DISPONIBLE EN META"};
const date=(value:string|null)=>value?new Date(value).toLocaleString("es-CL"):"Sin registro";
const blank:TemplateDraft={internalName:"",name:"",language:"es_CL",category:"",header:"",body:"",footer:"Clima Activa",description:"",bindings:[],buttons:[],purposeConfirmed:false};
function toDraft(t:ManagedTemplate):TemplateDraft {
  if(t.draft) return t.draft;
  const keys=[...new Set([...t.preview_body.matchAll(/{{\s*(\d+)\s*}}/g)].map(m=>m[1]))].sort((a,b)=>+a-+b);
  return {...blank,internalName:t.internal_name,name:t.meta_template_name,language:t.language,category:t.category,description:t.description,body:t.preview_body,
    header:t.components.find(c=>c.type==="HEADER")?.text || "",footer:t.components.find(c=>c.type==="FOOTER")?.text || "",
    bindings:keys.map(key=>t.variable_bindings.find(binding=>binding.key===key) || {key,field:"manual",example:""}),
    buttons:(t.components.find(c=>c.type==="BUTTONS")?.buttons || []).map(b=>({type:b.type,text:b.text,value:b.url || b.phone_number}))};
}

export function WhatsAppTemplatesPage({configuration=false}:{configuration?:boolean}) {
  const {user,isDemoMode}=useAuth(); const admin=user?.role==="administrador";
  const [data,setData]=useState<ManagementResponse|null>(null);const [error,setError]=useState("");const [notice,setNotice]=useState("");const [busy,setBusy]=useState(false);
  const [search,setSearch]=useState("");const [state,setState]=useState("");const [editor,setEditor]=useState<{row:ManagedTemplate|null;draft:TemplateDraft}|null>(null);
  const [approval,setApproval]=useState<ManagedTemplate|null>(null);const [confirmed,setConfirmed]=useState(false);const [rules,setRules]=useState("");
  const dialog=useRef<HTMLDialogElement>(null); const approvalDialog=useRef<HTMLDialogElement>(null);
  const load=useCallback(async(quiet=false)=>{if(isDemoMode)return;if(!quiet)setBusy(true);try{const result=await whatsappRequest<ManagementResponse>("whatsapp-template-management");setData(result);if(!quiet)setRules(JSON.stringify(result.policy,null,2));setError("");}catch(e){setError((e as Error).message);}finally{if(!quiet)setBusy(false);}},[isDemoMode]);
  const editing=Boolean(editor);
  useEffect(()=>{void load();},[load]);
  useEffect(()=>{const timer=window.setInterval(()=>{if(!document.hidden && !editing && !busy)void load(true);},15000);return()=>window.clearInterval(timer);},[load,editing,busy]);
  useEffect(()=>{if(editing)dialog.current?.showModal();},[editing]);
  useEffect(()=>{if(approval){setConfirmed(false);approvalDialog.current?.showModal();}},[approval]);
  async function operate(operation:string,body:Record<string,unknown>={}) {setBusy(true);setError("");setNotice("");try{await whatsappRequest("whatsapp-template-management",{operation,...body});setEditor(null);setApproval(null);setNotice(operation==="submit"?"Enviada a Meta. El estado se actualizará con la aprobación o rechazo.":operation==="sync"?"Plantillas sincronizadas con Meta.":"Cambios guardados.");await load();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  function change<K extends keyof TemplateDraft>(key:K,value:TemplateDraft[K]) {setEditor(old=>old?{...old,draft:{...old.draft,purposeConfirmed:false,[key]:value}}:old);}
  function bodyChanged(body:string) {setEditor(old=>{if(!old)return old;const keys=[...new Set([...body.matchAll(/{{\s*(\d+)\s*}}/g)].map(m=>m[1]))].sort((a,b)=>+a-+b);return {...old,draft:{...old.draft,body,purposeConfirmed:false,bindings:keys.map(key=>old.draft.bindings.find(b=>b.key===key)||{key,field:"manual",example:""})}};});}
  const status=(t:ManagedTemplate)=>t.local_state!=="SYNCED"?t.local_state:t.status;
  const visible=(data?.templates || []).filter(t=>(!state || status(t)===state) && `${t.internal_name} ${t.meta_template_name} ${t.preview_body}`.toLowerCase().includes(search.toLowerCase()));
  const messages=<>{error&&<p role="alert" className="wa-alert">{error}</p>}{notice&&<p role="status">{notice}</p>}{isDemoMode&&<p>Inicia sesión para administrar WhatsApp.</p>}</>;
  if(configuration)return <section className="wa-management"><h2>Configuración</h2>{messages}{data&&<><dl className="wa-config-grid"><div><dt>WABA ID</dt><dd>{data.configuration.wabaId}</dd></div><div><dt>Phone Number ID</dt><dd>{data.configuration.phoneNumberId}</dd></div><div><dt>Graph API</dt><dd>{data.configuration.graphVersion}</dd></div><div><dt>Reglas verificadas</dt><dd>{data.policy.verifiedAt}</dd></div><div><dt>Credenciales</dt><dd>Administradas exclusivamente en backend</dd></div></dl>{data.configuration.blockers.map(b=><p className="wa-alert" key={b}>{b}</p>)}<h3>Eventos requeridos</h3><ul>{data.configuration.webhookFields.map(f=><li key={f}><code>{f}</code></li>)}</ul><a href={data.policy.source} target="_blank" rel="noreferrer">Documentación oficial de Meta</a><details><summary>Reglas versionadas</summary><label>Configuración validada<textarea rows={15} value={rules} onChange={e=>setRules(e.target.value)}/></label><button className="primary-button" disabled={busy} onClick={()=>{try{const policy=JSON.parse(rules);void operate("policy",{policy});}catch{setError("El JSON de configuración no es válido.");}}}><Save size={17}/>Guardar reglas</button></details></>}</section>;
  return <section className="wa-management"><header className="wa-management-heading"><h2>Plantillas</h2><div>{admin&&<><button className="ghost-button" disabled={busy||isDemoMode} onClick={()=>void operate("sync")}><RefreshCw size={17}/>Sincronizar con Meta</button><button className="primary-button" disabled={!data||busy||isDemoMode} onClick={()=>setEditor({row:null,draft:{...blank,category:data?.policy.categories.find(c=>c==="MARKETING")||""}})}><Plus size={17}/>Nueva plantilla</button></>}</div></header>{messages}
    <div className="wa-template-filters"><label><Search size={18}/><input aria-label="Buscar plantilla" placeholder="Nombre o contenido" value={search} onChange={e=>setSearch(e.target.value)}/></label><select aria-label="Estado de plantilla" value={state} onChange={e=>setState(e.target.value)}><option value="">Todos los estados</option>{[...new Set((data?.templates||[]).map(status))].map(s=><option key={s} value={s}>{labels[s]||s}</option>)}</select></div>
    <table className="wa-template-table"><thead><tr><th>Nombre / Contenido</th><th>Categoría / Idioma</th><th>Estado</th><th>Meta ID / Fechas</th><th>Acciones</th></tr></thead><tbody>{visible.map(t=><tr key={t.id}>
      <td><strong>{t.internal_name}</strong><small>{t.meta_template_name}</small><p>{t.draft?.body || t.preview_body}</p>{t.description&&<small>{t.description}</small>}</td>
      <td>{t.draft?.category || t.category}<small>{t.language}</small></td>
      <td><span className={`wa-template-status wa-state-${status(t).toLowerCase()}`}>{labels[status(t)]||status(t)}</span>{t.draft&&t.meta_template_id&&<small>Versión Meta: {labels[t.status]||t.status}</small>}{t.rejected_reason&&<p className="wa-rejection">{t.rejected_reason}</p>}</td>
      <td><code>{t.meta_template_id || "Aún sin ID Meta"}</code><small>Creación: {date(t.created_at)}</small><small>Actualización: {date(t.updated_at)}</small><small>Sincronización: {date(t.last_synced_at)}</small></td>
      <td>{admin&&<><div className="wa-row-actions">
        <button className="ghost-button" aria-label={`Editar ${t.internal_name}`} title={t.editBlockedReason || "Editar borrador"} disabled={busy||Boolean(t.editBlockedReason)||["SUBMITTING","UNCERTAIN","ARCHIVED"].includes(t.local_state)} onClick={()=>setEditor({row:t,draft:toDraft(t)})}><Edit size={17}/></button>
        {t.draft&&t.local_state==="DRAFT"&&<button className="ghost-button" title={t.editBlockedReason || "Revisar envío a aprobación"} aria-label={`Revisar aprobación de ${t.internal_name}`} disabled={busy||Boolean(t.editBlockedReason)} onClick={()=>setApproval(t)}><Send size={17}/></button>}
        <button className="ghost-button" title="Archivar en el CRM" aria-label={`Archivar ${t.internal_name}`} disabled={busy||["SUBMITTING","UNCERTAIN","ARCHIVED"].includes(t.local_state)} onClick={()=>{if(window.confirm(`¿Archivar ${t.internal_name} en el CRM? No se eliminará en Meta.`))void operate("archive",{id:t.id,revision:t.revision});}}><Archive size={17}/></button>
      </div>{t.editBlockedReason&&<small>{t.editBlockedReason}</small>}</>}</td>
    </tr>)}</tbody></table>{!visible.length&&<p>{busy?"Cargando plantillas...":"No hay plantillas para este filtro."}</p>}
    {editor&&<dialog ref={dialog} className="wa-template-editor" onCancel={e=>{e.preventDefault();if(!busy)setEditor(null);}}><header><h2>{editor.row?"Editar borrador":"Nueva plantilla"}</h2><button className="ghost-button" aria-label="Cerrar editor" disabled={busy} onClick={()=>setEditor(null)}><X size={19}/></button></header>{error&&<p role="alert" className="wa-alert">{error}</p>}<form onSubmit={e=>{e.preventDefault();void operate("save",{id:editor.row?.id,revision:editor.row?.revision,draft:editor.draft});}}><div className="wa-editor-grid">
      <label>Nombre interno<input required value={editor.draft.internalName} maxLength={200} onChange={e=>change("internalName",e.target.value)}/></label><label>Nombre para Meta<input required pattern="[a-z0-9_]+" disabled={Boolean(editor.row?.meta_template_id)} value={editor.draft.name} maxLength={data?.policy.limits.name} onChange={e=>change("name",e.target.value)}/></label>
      <label>Idioma<select value={editor.draft.language} disabled={Boolean(editor.row?.meta_template_id)} onChange={e=>change("language",e.target.value)}>{data?.policy.languages.map(l=><option key={l}>{l}</option>)}</select></label><label>Categoría<select value={editor.draft.category} onChange={e=>change("category",e.target.value)}>{data?.policy.categories.map(c=><option key={c}>{c}</option>)}</select></label>
      <label className="wa-wide">Encabezado<input value={editor.draft.header} maxLength={data?.policy.limits.header} onChange={e=>change("header",e.target.value)}/></label><label className="wa-wide">Cuerpo<textarea required rows={5} value={editor.draft.body} maxLength={data?.policy.limits.body} onChange={e=>bodyChanged(e.target.value)}/></label><label className="wa-wide">Pie<input value={editor.draft.footer} maxLength={data?.policy.limits.footer} onChange={e=>change("footer",e.target.value)}/></label>
      <label className="wa-wide">Descripción interna<textarea rows={2} value={editor.draft.description} maxLength={2000} onChange={e=>change("description",e.target.value)}/></label></div>
      <h3>Variables</h3>{editor.draft.bindings.map((b,i)=><div className="wa-variable-row" key={b.key}><span>{`{{${b.key}}}`}</span><label>Dato CRM<select value={b.field} onChange={e=>change("bindings",editor.draft.bindings.map((v,j)=>j===i?{...v,field:e.target.value}:v))}>{data?.variableFields.map(f=><option key={f}>{f}</option>)}</select></label><label>Ejemplo ficticio para Meta<input required value={b.example} maxLength={1024} onChange={e=>change("bindings",editor.draft.bindings.map((v,j)=>j===i?{...v,example:e.target.value}:v))}/></label></div>)}
      <h3>Botones</h3>{editor.draft.buttons.map((b,i)=><div className="wa-button-row" key={i}><select aria-label={`Tipo botón ${i+1}`} value={b.type} onChange={e=>change("buttons",editor.draft.buttons.map((v,j)=>j===i?{...v,type:e.target.value}:v))}><option>QUICK_REPLY</option><option>URL</option><option>PHONE_NUMBER</option></select><input aria-label={`Texto botón ${i+1}`} required value={b.text} maxLength={data?.policy.limits.buttonText} onChange={e=>change("buttons",editor.draft.buttons.map((v,j)=>j===i?{...v,text:e.target.value}:v))}/>{b.type!=="QUICK_REPLY"&&<input aria-label={`Destino botón ${i+1}`} required value={b.value||""} onChange={e=>change("buttons",editor.draft.buttons.map((v,j)=>j===i?{...v,value:e.target.value}:v))}/>}<button type="button" className="ghost-button" aria-label={`Quitar botón ${i+1}`} onClick={()=>change("buttons",editor.draft.buttons.filter((_,j)=>j!==i))}><X size={16}/></button></div>)}<button className="ghost-button" type="button" disabled={editor.draft.buttons.length>=(data?.policy.limits.buttons||0)} onClick={()=>change("buttons",[...editor.draft.buttons,{type:"QUICK_REPLY",text:""}])}><Plus size={16}/>Agregar botón</button>
      <label className="wa-check"><input type="checkbox" checked={editor.draft.purposeConfirmed===true} onChange={e=>change("purposeConfirmed",e.target.checked)}/>Confirmo la finalidad de esta categoría. No hay promociones en una plantilla Utility.</label><footer><button type="button" className="ghost-button" disabled={busy} onClick={()=>setEditor(null)}>Cancelar</button><button className="primary-button" disabled={busy}><Save size={17}/>Guardar borrador</button></footer></form></dialog>}
    {approval?.draft&&<dialog ref={approvalDialog} className="wa-template-editor" onCancel={e=>{e.preventDefault();if(!busy)setApproval(null);}}><header><h2>Revisar plantilla para Meta</h2><button className="ghost-button" aria-label="Cerrar revisión" disabled={busy} onClick={()=>setApproval(null)}><X size={19}/></button></header>{error&&<p role="alert" className="wa-alert">{error}</p>}<p>{approval.meta_template_name} · {approval.draft.category} · {approval.language}</p><div className="wa-template-preview"><strong>{approval.draft.header}</strong><p>{approval.draft.body.replace(/{{\s*(\d+)\s*}}/g,(m,key)=>approval.draft?.bindings.find(b=>b.key===key)?.example || m)}</p><small>{approval.draft.footer}</small>{approval.draft.buttons.map((b,i)=><p key={i}>{b.text}{b.value?` · ${b.value}`:""}</p>)}</div><label className="wa-check"><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>Revisé el texto y sus ejemplos ficticios. Enviar a aprobación no envía mensajes a clientes.</label><footer><button className="ghost-button" disabled={busy} onClick={()=>setApproval(null)}>Cancelar</button><button className="primary-button" disabled={busy||!confirmed||!approval.draft.purposeConfirmed} onClick={()=>void operate("submit",{id:approval.id,revision:approval.revision,confirmSubmit:true})}><Send size={17}/>Enviar a Meta para aprobación</button></footer>{!approval.draft.purposeConfirmed&&<p>Confirma primero la finalidad y categoría en el editor.</p>}</dialog>}
  </section>;
}
