import { chileData, normalizeString } from "../../data/chileData";
import type {
  GeoComuna,
  GeoRegion,
  ProspectingSource,
  ProspectingTerritory,
  ProspectingWorkspace,
} from "../../types/crm";

const REGION_CODES = ["15", "01", "02", "03", "04", "05", "06", "07", "16", "08", "09", "14", "10", "11", "12", "13"];

export const DEFAULT_PROSPECTING_KEYWORDS = [
  "aire acondicionado",
  "climatizacion",
  "refrigeracion comercial",
  "instalacion HVAC",
  "servicio tecnico climatizacion",
];

export const SOURCE_DEFINITIONS: Array<{
  id: ProspectingSource;
  name: string;
  description: string;
  discovery: boolean;
  disabled?: boolean;
}> = [
  {
    id: "google_places",
    name: "Google Places API",
    description: "Descubrimiento territorial mediante la API oficial; por sí solo no habilita la importación.",
    discovery: true,
  },
  {
    id: "brave_search",
    name: "Brave Search API",
    description: "Descubrimiento web licenciado; requiere validar luego en el sitio oficial.",
    discovery: true,
  },
  {
    id: "official_website",
    name: "Sitio web oficial",
    description: "Valida contacto y domicilio con una fuente apta para almacenamiento permanente.",
    discovery: false,
  },
  {
    id: "amarillas",
    name: "Amarillas.cl",
    description: "Deshabilitado hasta contar con autorizacion o un feed oficial.",
    discovery: true,
    disabled: true,
  },
];

export const localGeoRegions: GeoRegion[] = chileData.map((region, index) => ({
  code: REGION_CODES[index],
  name: region.region,
}));

export const localGeoComunas: GeoComuna[] = chileData.flatMap((region, regionIndex) =>
  region.comunas.map((comuna, comunaIndex) => ({
    code: `local-${REGION_CODES[regionIndex]}-${String(comunaIndex + 1).padStart(3, "0")}`,
    regionCode: REGION_CODES[regionIndex],
    name: comuna,
    isLocalOnly: true,
  })),
);

function demoTerritory(regionCode: string, comunaNames: string[]): ProspectingTerritory {
  const region = localGeoRegions.find((item) => item.code === regionCode)!;
  const comunas = localGeoComunas.filter(
    (item) => item.regionCode === regionCode && comunaNames.some((name) => normalizeString(name) === normalizeString(item.name)),
  );

  return {
    regionCode,
    regionName: region.name,
    allCommunes: false,
    comunaCodes: comunas.map((item) => item.code),
    comunaNames: comunas.map((item) => item.name),
  };
}

export function createDemoProspectingWorkspace(): ProspectingWorkspace {
  const metropolitanTerritory = demoTerritory("13", ["Santiago", "Providencia", "Nunoa"]);
  const campaignId = "pros-campaign-demo-001";
  const runId = "pros-run-demo-001";

  return {
    regions: localGeoRegions,
    comunas: localGeoComunas,
    campaigns: [
      {
        id: campaignId,
        version: 1,
        name: "Instaladores HVAC Santiago Oriente",
        description: "Busqueda de instaladores y servicios tecnicos con contacto comercial verificable.",
        sector: "hvac",
        status: "active",
        keywords: ["aire acondicionado", "instalacion HVAC", "servicio tecnico climatizacion"],
        sources: ["google_places", "brave_search", "official_website"],
        territories: [metropolitanTerritory],
        targetTypes: ["tecnico", "instalador grande"],
        limits: { resultsPerTask: 20, maxCandidates: 1000 },
        createdBy: "demo-admin",
        createdAt: "2026-07-13T12:00:00-04:00",
        updatedAt: "2026-07-13T12:16:00-04:00",
      },
    ],
    runs: [
      {
        id: runId,
        campaignId,
        status: "running",
        snapshot: {
          schemaVersion: 1,
          campaignVersion: 1,
          campaignId,
          campaignName: "Instaladores HVAC Santiago Oriente",
          sector: "hvac",
          keywords: ["aire acondicionado", "instalacion HVAC", "servicio tecnico climatizacion"],
          sources: ["google_places", "brave_search", "official_website"],
          territories: [metropolitanTerritory],
          targetTypes: ["tecnico", "instalador grande"],
          limits: { resultsPerTask: 20, maxCandidates: 1000 },
          requestedBy: "demo-admin",
          requestedAt: "2026-07-13T12:05:00-04:00",
        },
        progress: { totalTasks: 18, completedTasks: 11, failedTasks: 1, candidatesFound: 24 },
        requestedBy: "demo-admin",
        createdAt: "2026-07-13T12:05:00-04:00",
        startedAt: "2026-07-13T12:05:08-04:00",
        completedAt: "",
        lastError: "Brave Search alcanzo temporalmente el limite de consultas para Providencia.",
      },
    ],
    candidates: [
      {
        id: "pros-candidate-demo-001",
        entityId: "pros-entity-demo-001",
        externalCandidateId: "demo-agent-candidate-001",
        campaignId,
        runId,
        name: "Clima Andes Servicios",
        legalName: "Clima Andes Servicios SpA",
        rut: "",
        businessLine: "Instalacion y mantencion de sistemas de aire acondicionado para comercios.",
        companyType: "instalador grande",
        website: "https://clima-andes.example",
        phone: "+56 2 2345 6789",
        email: "contacto@clima-andes.example",
        score: 92,
        reviewStatus: "pending",
        locations: [
          {
            id: "pros-location-demo-001",
            kind: "casa_matriz",
            regionCode: "13",
            regionName: "Region Metropolitana de Santiago",
            comunaCode: metropolitanTerritory.comunaCodes[1] ?? metropolitanTerritory.comunaCodes[0],
            comunaName: "Providencia",
            address: "Av. Nueva Providencia 1234",
            isPrimary: true,
          },
        ],
        evidence: [
          {
            id: "pros-evidence-demo-001",
            source: "google_places",
            url: "https://www.google.com/maps",
            externalId: "demo-place-001",
            field: "name",
            value: "Clima Andes Servicios",
            confidence: 0.96,
            observedAt: "2026-07-13T12:09:00-04:00",
            retentionAllowed: false,
          },
          {
            id: "pros-evidence-demo-001b",
            source: "google_places",
            url: "https://www.google.com/maps",
            externalId: "demo-place-001",
            field: "location.comuna_code",
            value: metropolitanTerritory.comunaCodes[1] ?? metropolitanTerritory.comunaCodes[0],
            confidence: 0.98,
            observedAt: "2026-07-13T12:09:00-04:00",
            retentionAllowed: false,
          },
          {
            id: "pros-evidence-demo-001c",
            source: "google_places",
            url: "https://www.google.com/maps",
            externalId: "demo-place-001",
            field: "location.comuna_name",
            value: "Providencia",
            confidence: 0.98,
            observedAt: "2026-07-13T12:09:00-04:00",
            retentionAllowed: false,
          },
          {
            id: "pros-evidence-demo-002",
            source: "official_website",
            url: "https://clima-andes.example/contacto",
            externalId: "",
            field: "email",
            value: "contacto@clima-andes.example",
            confidence: 0.94,
            observedAt: "2026-07-13T12:10:00-04:00",
            retentionAllowed: true,
          },
          {
            id: "pros-evidence-demo-002b",
            source: "official_website",
            url: "https://clima-andes.example",
            externalId: "",
            field: "business_line",
            value: "Instalacion y mantencion de sistemas de aire acondicionado para comercios.",
            confidence: 0.95,
            observedAt: "2026-07-13T12:10:00-04:00",
            retentionAllowed: true,
          },
        ],
        importEligible: true,
        importableLocationIndexes: [0],
        reviewFlags: [],
        possibleDuplicateExternalCandidateId: "",
        possibleDuplicateCompanyId: "",
        linkedCompanyId: "",
        reviewNotes: "",
        firstSeenAt: "2026-07-13T12:09:00-04:00",
        lastSeenAt: "2026-07-13T12:10:00-04:00",
      },
      {
        id: "pros-candidate-demo-002",
        entityId: "pros-entity-demo-002",
        externalCandidateId: "demo-agent-candidate-002",
        campaignId,
        runId,
        name: "Refrigera Express",
        legalName: "Refrigera Express Chile SpA",
        rut: "76.901.300-K",
        businessLine: "Tienda e instalacion de equipos de refrigeracion comercial.",
        companyType: "tienda comercial",
        website: "https://example.org",
        phone: "+56 32 222 2111",
        email: "ventas@refrigeraexpress.example",
        score: 87,
        reviewStatus: "possible_duplicate",
        locations: [
          {
            id: "pros-location-demo-002",
            kind: "sucursal",
            regionCode: "13",
            regionName: "Region Metropolitana de Santiago",
            comunaCode: metropolitanTerritory.comunaCodes[0],
            comunaName: "Santiago",
            address: "San Diego 842",
            isPrimary: true,
          },
        ],
        evidence: [
          {
            id: "pros-evidence-demo-003",
            source: "google_places",
            url: "https://www.google.com/maps",
            externalId: "",
            field: "name",
            value: "Refrigera Express",
            confidence: 0.93,
            observedAt: "2026-07-13T12:12:00-04:00",
            retentionAllowed: false,
          },
          {
            id: "pros-evidence-demo-003b",
            source: "google_places",
            url: "https://www.google.com/maps",
            externalId: "",
            field: "location.comuna_code",
            value: metropolitanTerritory.comunaCodes[0],
            confidence: 0.9,
            observedAt: "2026-07-13T12:12:00-04:00",
            retentionAllowed: false,
          },
          {
            id: "pros-evidence-demo-003c",
            source: "google_places",
            url: "https://www.google.com/maps",
            externalId: "",
            field: "location.comuna_name",
            value: "Santiago",
            confidence: 0.9,
            observedAt: "2026-07-13T12:12:00-04:00",
            retentionAllowed: false,
          },
          {
            id: "pros-evidence-demo-003d",
            source: "google_places",
            url: "https://www.google.com/maps",
            externalId: "",
            field: "website",
            value: "https://example.org",
            confidence: 0.91,
            observedAt: "2026-07-13T12:13:00-04:00",
            retentionAllowed: false,
          },
          {
            id: "pros-evidence-demo-003e",
            source: "google_places",
            url: "https://www.google.com/maps",
            externalId: "",
            field: "business_line",
            value: "Tienda e instalacion de equipos de refrigeracion comercial.",
            confidence: 0.89,
            observedAt: "2026-07-13T12:13:00-04:00",
            retentionAllowed: false,
          },
        ],
        importEligible: false,
        importableLocationIndexes: [],
        reviewFlags: ["insufficient_permanent_evidence", "location_0_temporary_evidence"],
        possibleDuplicateExternalCandidateId: "",
        possibleDuplicateCompanyId: "cmp-003",
        linkedCompanyId: "",
        reviewNotes: "Coincidencia exacta de dominio con una empresa existente.",
        firstSeenAt: "2026-07-13T12:12:00-04:00",
        lastSeenAt: "2026-07-13T12:13:00-04:00",
      },
      {
        id: "pros-candidate-demo-003",
        entityId: "pros-entity-demo-003",
        externalCandidateId: "demo-agent-candidate-003",
        campaignId,
        runId,
        name: "Termica Central",
        legalName: "",
        rut: "",
        businessLine: "Servicio tecnico de climatizacion residencial y comercial.",
        companyType: "tecnico",
        website: "",
        phone: "+56 9 8765 4321",
        email: "",
        score: 76,
        reviewStatus: "possible_duplicate",
        locations: [
          {
            id: "pros-location-demo-003",
            kind: "casa_matriz",
            regionCode: "13",
            regionName: "Region Metropolitana de Santiago",
            comunaCode: metropolitanTerritory.comunaCodes[2] ?? metropolitanTerritory.comunaCodes[0],
            comunaName: "Nunoa",
            address: "Irarrázaval 2600",
            isPrimary: true,
          },
          {
            id: "pros-location-demo-004",
            kind: "sucursal",
            regionCode: "13",
            regionName: "Region Metropolitana de Santiago",
            comunaCode: metropolitanTerritory.comunaCodes[1] ?? metropolitanTerritory.comunaCodes[0],
            comunaName: "Providencia",
            address: "Av. Los Leones 1450",
            isPrimary: false,
          },
        ],
        evidence: [
          {
            id: "pros-evidence-demo-004",
            source: "google_places",
            url: "https://www.google.com/maps",
            externalId: "demo-place-003",
            field: "name",
            value: "Termica Central",
            confidence: 0.9,
            observedAt: "2026-07-13T12:15:00-04:00",
            retentionAllowed: false,
          },
          {
            id: "pros-evidence-demo-004b",
            source: "google_places",
            url: "https://www.google.com/maps",
            externalId: "demo-place-003",
            field: "location.comuna_code",
            value: metropolitanTerritory.comunaCodes[2] ?? metropolitanTerritory.comunaCodes[0],
            confidence: 0.92,
            observedAt: "2026-07-13T12:15:00-04:00",
            retentionAllowed: false,
          },
          {
            id: "pros-evidence-demo-004c",
            source: "google_places",
            url: "https://www.google.com/maps",
            externalId: "demo-place-003",
            field: "location.comuna_name",
            value: "Nunoa",
            confidence: 0.92,
            observedAt: "2026-07-13T12:15:00-04:00",
            retentionAllowed: false,
          },
          {
            id: "pros-evidence-demo-004d",
            source: "google_places",
            url: "https://www.google.com/maps",
            externalId: "demo-place-003",
            field: "phone",
            value: "+56 9 8765 4321",
            confidence: 0.88,
            observedAt: "2026-07-13T12:15:00-04:00",
            retentionAllowed: false,
          },
          {
            id: "pros-evidence-demo-004e",
            source: "google_places",
            url: "https://www.google.com/maps",
            externalId: "demo-place-003",
            field: "business_line",
            value: "Servicio tecnico de climatizacion residencial y comercial.",
            confidence: 0.86,
            observedAt: "2026-07-13T12:15:00-04:00",
            retentionAllowed: false,
          },
        ],
        importEligible: true,
        importableLocationIndexes: [0],
        reviewFlags: ["location_1_temporary_evidence"],
        possibleDuplicateExternalCandidateId: "demo-agent-candidate-001",
        possibleDuplicateCompanyId: "",
        linkedCompanyId: "",
        reviewNotes: "El agente detectó una similitud difusa con otro candidato; requiere revisión humana.",
        firstSeenAt: "2026-07-13T12:15:00-04:00",
        lastSeenAt: "2026-07-13T12:15:00-04:00",
      },
    ],
    events: [
      {
        id: "pros-event-demo-001",
        runId,
        taskId: "task-001",
        createdAt: "2026-07-13T12:05:08-04:00",
        level: "info",
        stage: "planificacion",
        message: "Ejecucion tomada por el agente. Se generaron 18 tareas territoriales.",
        metrics: { totalTasks: 18 },
      },
      {
        id: "pros-event-demo-002",
        runId,
        taskId: "task-004",
        createdAt: "2026-07-13T12:09:00-04:00",
        level: "info",
        stage: "busqueda",
        source: "google_places",
        keyword: "instalacion HVAC",
        comunaName: "Providencia",
        message: "Consulta completada: 11 resultados, 5 candidatos validos y 2 duplicados.",
        metrics: { results: 11, accepted: 5, duplicates: 2 },
      },
      {
        id: "pros-event-demo-003",
        runId,
        taskId: "task-009",
        createdAt: "2026-07-13T12:13:00-04:00",
        level: "warning",
        stage: "cuota",
        source: "brave_search",
        keyword: "aire acondicionado",
        comunaName: "Providencia",
        message: "Limite temporal de consultas. La tarea quedo programada para reintento.",
        metrics: { retry: 1 },
      },
      {
        id: "pros-event-demo-004",
        runId,
        taskId: "task-011",
        createdAt: "2026-07-13T12:16:00-04:00",
        level: "info",
        stage: "enriquecimiento",
        source: "official_website",
        comunaName: "Santiago",
        message: "Se verificaron sitio web y correo comercial para 7 candidatos.",
        metrics: { verified: 7 },
      },
    ],
  };
}
